# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - run: npm install @openapitools/openapi-generator-cli -g
      - run: npx @openapitools/openapi-generator-cli generate -i du-map-api.yaml -g spring -o spring --additional-properties=interfaceOnly=true,groupId=de.xairooo.du,artifactId=du-map-api,basePackage=de.xairooo.du.map,apiPackage=de.xairooo.du.map.api,modelPackage=de.xairooo.du.map.model,developerName=xairooo,developerEmail=xairooo@xairooo.de,scmConnection=scm:git:git@github.com:xairooo/du-map-api.git

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/spring # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file spring/pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -Dmaven.resolver.transport=wagon deploy -B -s $GITHUB_WORKSPACE/spring/settings.xml --file spring/pom.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/xairooo/du-map-api
        env:
          GITHUB_TOKEN: ${{ github.token }}
